name: Deploy Java App to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Create deployment package
        run: |
          cp target/*.jar deployment/
          echo "web: java -Dserver.port=\$PORT -jar *.jar" > deployment/Procfile
          cd deployment
          zip -r ../deploy.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          S3_KEY="java-app-${TIMESTAMP}.zip"
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET }}/${S3_KEY}
          echo "S3_KEY=${S3_KEY}" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --version-label ${GITHUB_SHA:0:8} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=${{ env.S3_KEY }}
          
          aws elasticbeanstalk update-environment \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
            --version-label ${GITHUB_SHA:0:8}

      - name: Wait for deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --environment-names ${{ secrets.EB_ENVIRONMENT_NAME }}